### PR TITLE
Allow profile sections to take up more height

### PR DESCRIPTION
**Pull request by nlitwin**
## Description

**Issue:** Closes: #223 

Fixes this described in the issue above: 

## Subtasks

- [x] I have added this PR to the Journaly Kanban project ✅
- [x] Make profile details and recent posts take up the height they need to not have their content spill over
- [x] Show `Recent Posts` title on desktop too

### CODE REVIEW

**Comment by robin-macpherson** [comment]
Hmm let's see, just want to make sure I understand the PR/intent fully. Ideally we want the whole profile to be visible unless the height of the viewport is really low. So visually I would prefer that we constrain the height from expanding beyond a certain point. For example as we chatted about in person yesterday, the problem in the first screenshot ideally shouldn't occur in the first place because the posts should kind of disappear and you should be able to scroll up and down through the post list inside of that right section, does that make sense?

**Comment by robin-macpherson** [comment]
So if I'm understanding the current PR/intent correctly (I definitely might be missing something so feel free to correct me!) I would actually prefer we try to fix the central issue which is that the post list explodes/overflows out of the section and see if we can implement some scrolling that is contained inside the `PostList`

**Comment by robin-macpherson** [comment]
I wonder how quickly we could implement a "Read more..." for bio's that are longer than a certain amount. But the other option that might just be both simpler to implement and also simpler for the user because it sets an expectation is to have a max character length on the bio. We could start by just using whatever the char count is of the demo we have since we've built/designed around that! Whatcha think!? 😄

**Comment by nlitwin** [comment]
@robin-macpherson Thanks for the comments! I'm working on the PostList now to make it scroll if there are more posts than fit the PostList container 👍  We will definitely need to set a max length on the bio though like you said so that the profile details don't get taller than the max-width of the PostList that allows it to scroll.

I think we could add the max length to the bio in another PR, since that max length needs to be enforced in the Settings page when users update their bio there, which isn't wired up yet. What do you think? 😄

**Comment by nlitwin** [comment]
I updated the PR description with a new GIF :D

**Comment by robin-macpherson** [comment]
> @robin-macpherson Thanks for the comments! I'm working on the PostList now to make it scroll if there are more posts than fit the PostList container 👍 We will definitely need to set a max length on the bio though like you said so that the profile details don't get taller than the max-width of the PostList that allows it to scroll.
> 
> I think we could add the max length to the bio in another PR, since that max length needs to be enforced in the Settings page when users update their bio there, which isn't wired up yet. What do you think? 😄

Sounds good to me! I can handle the max length then because I was going to hook up those settings today potentially while adding in the image uploading for profile image! I'll keep you updated on that!

**Pull request merged**
