### PR TITLE
New Round Of Slate Upgrades

### PR DESCRIPTION
**Pull request by robin-macpherson**
## Description

I was checking recent Slate minor releases and I saw a few PRs that look potentially interesting, for example [this](https://github.com/ianstormtaylor/slate/pull/4627) - and thought it would be worth keeping our Slate versions up-to-date, particularly keeping an eye on the key issues that are impacting us. I've also reached out to a fantastic Slate contributor to ask directly if his recent work might relate to our current Android spellcheck issue.

## Subtasks

- [x] I have added this PR to the Journaly Kanban project ✅
- [x] Make the updates
- [x] Test for regressions or hopefully improvements 🤞🏼

### Deployment Checklist

- [N/A] 🚨 Publish new j-db-client version and update in both `web` and `j-mail`
- [N/A] 🚨 Deploy migs to stage
- [ ] 🚨 Deploy code to stage
- [N/A] 🚨 DEPLOY `j-mail` to stage
- [N/A] 🚨 Deploy migs to prod
- [ ] 🚨 Deploy code to prod
- [N/A] 🚨 DEPLOY `j-mail` TO PROD

### CODE REVIEW

**Comment by robin-macpherson** [comment]
@LindasLinguas would you mind re-testing the Android spell-check issue you found last time over at stage.journaly.com whenever you next have time? 😄🙏🏼 (please note we recently had to reset the data on Stage, so some recently created posts might be gone)

**Comment by LindasLinguas** [comment]
The cursor jumping still happens. Had there been other issues?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by robin-macpherson** [comment]
@LindasLinguas OK got it, thank you for checking! I have started reaching out to some really excellent Android specialists I have seen making great contributions to see if they can help to point me in the right direction in starting to investigate the spellcheck problem. Although it also seems that @rickyweb was still having significant issues typing in Korean back with #670 , so I will also try my best to see if there's anything I can do to investigate those issues in Slate or reach out to folks to help guide me

**Comment by robin-macpherson** [comment]
@Lanny think it makes sense to merge these minor updates in for now? I'll continue monitoring stuff over in the Slate repo closely in the meantime.

**Comment by robin-macpherson** [comment]
Just FYI I just brought in a couple of new changes with a minor release to `slate` and `slate-react` that came out a couple of days ago (`0.70.0`). I don't think there's anything there that looks like it will positively impact any of our bugs but thought it made sense to bring them in since this is still open

**Comment by robin-macpherson** [comment]
Hi @LindasLinguas ! Would you mind re-testing the same way you did before, with the same link: https://journaly-git-latest-slate-upgrades-journaly.vercel.app ? I just brought in some new fixes that look like they may be relevant.

@Lanny notable PRs/fixes from the most recent updates:
- [Support SSR for autoCorrect, spellCheck and autoCapitalize.
Fixes prop mismatch between server and client.](https://github.com/ianstormtaylor/slate/pull/4682) (this at least addresses a warning/issue we've experienced re: SSR prop mismatches - really nice, clear, and instructive PR too!)
- [ Fixed the issue where the cursor jumps more than one character unexpectedly](https://github.com/ianstormtaylor/slate/pull/4671)

**Comment by robin-macpherson** [comment]
Hi @LindasLinguas ! I just wanted to check in on the status of testing here? I just replied to your email about the Grammarly bug that came in on the same day I tagged you here, I couldn't quite tell if that was happening on production or if it was related to your testing on this branch with the most recent updates, because I saw there are some Grammarly-related updates in this branch. I hope you're having a great week!

**Pull request merged**
