### PR TITLE
Change resetTokenExpiry type to integer in the first migration

### LINKED ISSUE #408: ERROR: column "resetTokenExpiry" cannot be cast automatically to type integer
#### Description

After runs `npm run prisma:generate` I'm getting an annoying database error that is blocking me to start contributing.

Screen Shot 2020-12-31 at 08 48 11

#### Repro Steps

Following the [Initial Setup](https://github.com/Journaly/journaly#initial-setup) instructions, it's happening in the fourth step.

FYI: I thought that it was happening because I was running my Postgres through a docker image. But, to make sure that it hadn't any relation to it I installed Postgres on my host machine and it still happening.

#### Versions
- postgres (PostgreSQL): 13.1
- npm: 7.0.14
- node: v15.3.0
- OS: macOS Catalina

### PR DESCRIPTION
**Pull request by davidsonsns**
Very excited guys to start helping the project! Please let me know if my PR makes sense and even if there is something to improve.

## Description

**Issue:** closes #408 

Currently, if you run `npm run migrate:up` you will get an error related to typecasting. It's related to the column `resetTokenExpiry` which has `DateTime` type on the first migration and the migration `20200919143307-update-reset-token-expiry-type` tries to change it to `Int`. My guess is there isn't an implicit way to do that with Postgres and even a way to fix it with prisma, at least so far. Manipulating the migrations manually was the only way that I found to make it works fine. 

## Subtasks

- [x] I have added this PR to the Journaly Kanban project ✅
- [x] Removed the migration `20200919143307-update-reset-token-expiry-type`
- [x] Removed `20200919143307-update-reset-token-expiry-type` on `prisma/migrations/migrate.lock`
- [x] Changed `resetTokenExpiry` type in all migrations from `20200624211600-initial` to `20200910205210-add-topic-translation-table`

## Migrations

Even with all work related to migrations made, isn't required any extra work because it was applied to the first migration. So, if

### CODE REVIEW

**Review by robin-macpherson — COMMENTED** [review]
Thanks for this @davidsonsns and welcome to the repo! If you'd like the "Journaly Contributor" badge on your Journaly profile, please let me know your username so we can add it for you 😊

The PR looks great, we'd like to do a bit of testing just to be safe and then will merge it in or provide feedback if needed.

**Comment by Lanny** [comment]
Hi @davidsonsns, thanks for this PR! Creating a fresh DB was broken when we upgraded prisma and we definitely need to fix this. It fell by the wayside since we had working local DBs and prod never needs to restart from scratch but definitely a roadblock to new folks coming in so really appreciate you looking at it.

Deleting mig `20200919143307-update-reset-token-expiry-type` does cause some some problems for existing DBs however, restarting dev DBs is fine but it breaks our ability to apply new migrations to prod which is an issue. Output when trying to `npm run migrate:up` with a DB that's in sync with prod:

```
[ryanjenkins:~/journaly]$ npm run migrate:up                                                                        

> journaly@1.0.0 migrate:up /Users/ryanjenkins/journaly
> npm explore '@journaly/j-db-client' -- npm run migrate:up


> @journaly/j-db-client@1.0.0 migrate:up /Users/ryanjenkins/journaly/j-db-client
> prisma migrate up --experimental


Prisma schema loaded from prisma/schema.prisma
Error: There are more migrations in the database than locally. This must not happen.
Local migration ids: 20200624211600-initial, 20200625141833-remove-language-learning-unique-constraint-on-user-id, 20200702185801-fix-issues, 20200805064655-add-published-at-to-posts, 20200813092954-add-post-comment, 20200816171330-add-thread-subscription-table, 20200908095206-add-thanks-and-db-constraints, 20200910205210-add-topic-translation-table, 20200923094139-add-user-follows-m2m, 20201002152245-add-archived-field-to-threads, 20201026144537-new-language-relation-model, 20201101185157-add-badges-table, 20201108184902-add-code-contributor-and-10-post-badges, 20201209170034-change-social-media-model, 20201218045952-add-post-comment-subscription-table, 20201223164158-add-language-dev-name, 20201223171239-replace-location-model, 20201228152243-add-published-language-level.
Remote migration ids: 20200624211600-initial, 20200625141833-remove-language-learning-unique-constraint-on-user-id, 20200702185801-fix-issues, 20200805064655-add-published-at-to-posts, 20200813092954-add-post-comment, 20200816171330-add-thread-subscription-table, 20200908095206-add-thanks-and-db-constraints, 20200910205210-add-topic-translation-table, 20200919143307-update-reset-token-expiry-type, 20200923094139-add-user-follows-m2m, 20201002152245-add-archived-field-to-threads, 20201026144537-new-language-relation-model, 20201101185157-add-badges-table, 20201108184902-add-code-contributor-and-10-post-badges, 20201209170034-change-social-media-model, 20201218045952-add-post-comment-subscription-table, 20201223164158-add-language-dev-name, 20201223171239-replace-location-model, 20201228152243-add-published-language-level
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @journaly/j-db-client@1.0.0 migrate:up: `prisma migrate up --experimental`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @journaly/j-db-client@1.0.0 migrate:up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ryanjenkins/.npm/_logs/2021-01-04T02_23_34_916Z-debug.log
npm ERR! weird error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! journaly@1.0.0 migrate:up: `npm explore '@journaly/j-db-client' -- npm run migrate:up`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the journaly@1.0.0 migrate:up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ryanjenkins/.npm/_logs/2021-01-04T02_23_34_945Z-debug.log
```

If you want to repro locally, here's a dump of my dev DB: https://gist.github.com/Lanny/b3c74d253e88232f696ad9d667686a45 (it assumes the role/user `robin` owns the tables, you can either edit the SQL dump or create/use that role (latter is probably easier)). If you drop that file in your repo and do `npm run db:restore` it'll load the snapshot and you should get the same output as above.

As for a solution, I think if you restore the deleted migration (and revert the change to migration.lock file), then edit `j-db-client/prisma/migrations/20200919143307-update-reset-token-expiry-type/steps.json` to have `steps` be an empty array it should fix the situation. Existing DBs will see the migration exists/is consistent with their state and be happy, and new DBs will be able to cleanly apply all the migs.

**Comment by robin-macpherson** [comment]
Thanks a lot for this, @Lanny ! At this point, I am wondering if we should just go ahead and start a new migration history and then baseline our prod DB? We could test the waters with a copy of the DB, and then we could perhaps also place the current migrations in a different directory if we want to explicitly keep that history for now?

Here is the guide on doing this if we were to go that route: https://www.prisma.io/docs/guides/prisma-guides/prisma-migrate-guides/add-prisma-migrate-to-a-project

**Comment by davidsonsns** [comment]
Thanks a lot, both of you guys!

@robin-macpherson that badge idea is definitely amazing! Of course, it will be great!

@Lanny first thing, thank you so much for your review. I just saw that isn't an issue related to the Prisma version. Just clarifying, this message you got is happening because Prisma creates the table `_Migration` that handles migrations history. So, it hopes that all migrations there will be also on the `migrations` folder. 

A way that I found to fix it was to remove the row with the migration `20200919143307-update-reset-token-expiry-type`. 
Here the SQL ran: `DELETE FROM "public"."_Migration" WHERE name='20200919143307-update-reset-token-expiry-type';`.
A bad point in doing that is because we lost a register of the migration. But, it fixed the issue reported.

What do you guys think about it? Does it make sense?

**Comment by robin-macpherson** [comment]
@davidsonsns I think that approach makes sense to me. After all, that particular migration was very minor and prior to it, that field was completely unused by the application. What do you think @Lanny ?

Also @davidsonsns can you let me know your Journaly handle so I can make sure you get the badge? 😄

**Comment by davidsonsns** [comment]
@robin-macpherson just created it now. Probably you'll be able to find me there as `davidsonsns`

🚀

**Comment by Lanny** [comment]
> @Lanny first thing, thank you so much for your review. I just saw that isn't an issue related to the Prisma version. Just clarifying, this message you got is happening because Prisma creates the table `_Migration` that handles migrations history. So, it hopes that all migrations there will be also on the `migrations` folder.

Right, the migration `20200919143307-update-reset-token-expiry-type` was broken by the prisma version upgrade, but the issue with applying the migs against an existing DB doesn't have anything to do with the version, just the absence of an expected mig

> A way that I found to fix it was to remove the row with the migration `20200919143307-update-reset-token-expiry-type`.
> Here the SQL I ran: `DELETE FROM "public"."_Migration" WHERE name='20200919143307-update-reset-token-expiry-type';`.
> A bad point in doing that is because we lost a register of the migration. But, it fixed the issue reported.

Ah, yeah, that would do it. That works for me, just a heads up @robin-macpherson when this merges you'll want to manually run the SQL above against prod

**Review by Lanny — APPROVED** [review]

**Pull request merged**
